module.exports = {
	config: ( typescript ) => [
		"const node = require(\"@sveltejs/adapter-node\")",
		typescript ? "const sveltePreprocess = require(\"svelte-preprocess\")" : null,
		"",
		"module.exports = {",
		typescript ? "\tpreprocess: sveltePreprocess(),\n" : null,
		"\tkit: {",
		"\t\tadapter: node()",
		"\t}",
		"}",
		""
	].filter(( line ) => line != null).join("\n"),
	css: [
		"@import url(\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\");",
		"",
		":root {",
		"\tfont-family: Roboto, -apple-system, Arial, sans-serif;",
		"}",
		"",
		"*:focus {",
		"\toutline: none;",
		"}",
		""
	].join("\n"),
	app: [
		"<!DOCTYPE html>",
		"<html lang=\"en\">",
		"<head>",
		"\t<meta charset=\"utf-8\" />",
		"\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
		"",
		"\t%svelte.head%",
		"</head>",
		"<body>",
		"\t%svelte.body%",
		"</body>",
		"</html>",
		""
	].join("\n"),
	$layout: ( typescript ) => [
		`<script${typescript ? " lang=\"ts\"" : ""}>`,
		"\timport \"../app.css\"",
		"</script>",
		"",
		"",
		"<div class=\"main\">",
		"\t<slot />",
		"</div>",
		""
	].join("\n"),
	index: ( typescript ) => [
		`<script context=\"module\"${typescript ? " lang=\"ts\"" : ""}>`,
		"\texport const prerender = true",
		"</script>",
		"",
		"",
		"<h1>hello world</h1>",
		""
	].join("\n"),
	robots: [
		"# https://www.robotstxt.org/robotstxt.html",
		"User-agent: *",
		"Disallow:",
		""
	].join("\n"),
	gitignore: [
		"",
		"# svelte",
		"/.svelte/",
		"/build/",
		""
	].join("\n"),
	ts: {
		tsconfig: [
			"{",
			"\t\"compilerOptions\": {",
			"",
			"\t\t/* - project options - */",
			"\t\t\"allowJs\": true,",
			"\t\t\"checkJs\": true,",
			"\t\t\"isolatedModules\": true,",
			"\t\t\"lib\": [\"es2020\"],",
			"\t\t\"module\": \"es2020\",",	
			"\t\t\"removeComments\": true,",
			"\t\t\"sourceMap\": true,",
			"\t\t\"target\": \"es2019\",",
			"",
			"\t\t/* - strict checks - */",
			"\t\t\"alwaysStrict\": true,",
			"\t\t\"noImplicitAny\": true,",
			"\t\t\"noImplicitThis\": true,",
			"\t\t\"strict\": true,",
			"\t\t\"strictBindCallApply\": true,",
			"\t\t\"strictFunctionTypes\": true,",
			"\t\t\"strictNullChecks\": true,",
			"\t\t\"strictPropertyInitialization\": true,",
			"",
			"\t\t/* - linter checks - */",
			"\t\t\"noImplicitReturns\": true,",
			"\t\t\"noFallthroughCasesInSwitch\": true,",
			"\t\t\"noUncheckedIndexedAccess\": true,",
			"\t\t\"noUnusedLocals\": true,",
			"\t\t\"noUnusedParameters\": true,",
			"",
			"\t\t/* - module resolution - */",
			"\t\t\"baseUrl\": \".\",",
			"\t\t\"esModuleInterop\": true,",
			"\t\t\"moduleResolution\": \"node\",",
			"\t\t\"paths\": {",
			"\t\t\t\"lib/*\": [\"src/lib/*\"]",
			"\t\t},",
			"",
			"\t\t/* - advanced - */",
			"\t\t\"forceConsistentCasingInFileNames\": true,",
			"\t\t\"importsNotUsedAsValues\": \"error\",",
			"\t\t\"resolveJsonModule\": true,",
			"\t\t\"skipLibCheck\": true,",
			"\t},",
			"\t\"include\": [\"src/**/*.d.ts\", \"src/**/*.js\", \"src/**/*.ts\", \"src/**/*.svelte\"]",
			"}",
			""
		].join("\n"),
		global: [
			"/// <reference types=\"@sveltejs/kit\" />",
			"/// <reference types=\"svelte\" />",
			"/// <reference types=\"vite/client\" />",
			""
		].join("\n")
	}
}
