module.exports = {
	__error: [
		"<script context=\"module\">",
		"\texport function load ({ status, error }) {",
		"\t\treturn {",
		"\t\t\tprops: {",
		"\t\t\t\tstatus,",
		"\t\t\t\terror",
		"\t\t\t}",
		"\t\t}",
		"\t}",
		"",
		"\texport const hydrate = false",
		"</script>",
		"",
		"<script>",
		"\texport let status",
		"\texport let error",
		"</script>",
		"",
		"",
		"<svelte:head>",
		"\t<title>{status}: {error.message}</title>",
		"</svelte:head>",
		"",
		"<div class=\"container\">",
		"\t<div class=\"code\">{status}</div>",
		"\t<div class=\"message\">{error.message}</div>",
		"</div>",
		"",
		"<div class=\"footer\">",
		"\t<div class=\"button\" on:click={() => window.location.reload()}>reload</div>",
		"\t<div class=\"button\" on:click={() => window.history.back()}>back</div>",
		"\t<a class=\"button\" href=\"/\">home</a>",
		"</div>",
		"",
		"",
		"<style>",
		"",
		"\t.button, .code {",
		"\t\tuser-select: none;",
		"\t}",
		"",
		"\t@media only screen and (max-width: 750px) {",
		"\t\t.container {",
		"\t\t\tpadding-top: 15vh !important;",
		"\t\t}",
		"",
		"\t\t.code {",
		"\t\t\theight: 50vw !important;",
		"",
		"\t\t\tfont-size: 50vw !important;",
		"\t\t}",
		"",
		"\t\t.message {",
		"\t\t\tfont-size: 6vw !important;",
		"\t\t}",
		"\t}",
		"",
		"\t@media only screen and (max-height: 800px) {",
		"\t\t.container {",
		"\t\t\tpadding-top: 8vh !important;",
		"\t\t}",
		"\t}",
		"",
		"\t@media only screen and (max-height: 600px) {",
		"\t\t.container {",
		"\t\t\tpadding-top: 10vh !important;",
		"\t\t}",
		"",
		"\t\t.code {",
		"\t\t\theight: 45vh !important;",
		"",
		"\t\t\tfont-size: 45vh !important;",
		"\t\t}",
		"",
		"\t\t.message {",
		"\t\t\tfont-size: 5vh !important;",
		"\t\t}",
		"\t}",
		"",
		"\t.container {",
		"\t\tpadding: 10vh 0 0;",
		"\t}",
		"",
		"\t.code {",
		"\t\theight: 45vh;",
		"",
		"\t\tcolor: #ff806066;",
		"\t\tfont-size: 45vh;",
		"\t\ttext-align: center;",
		"\t}",
		"",
		"\t.message {",
		"\t\ttop: 50vh;",
		"",
		"\t\tfont-size: 5vh;",
		"\t\ttext-align: center;",
		"\t}",
		"",
		"\t.footer {",
		"\t\tposition: absolute;",
		"\t\tbottom: 40px;",
		"\t\tleft: 5vw;",
		"\t\tright: 5vw;",
		"",
		"\t\tdisplay: grid;",
		"\t\tgrid-template-columns: 1fr 1fr 1fr;",
		"",
		"\t\tborder-top: 4px solid #3000e040;",
		"\t}",
		"",
		"\t.button {",
		"\t\theight: calc(3vh + 30px);",
		"",
		"\t\tdisplay: grid;",
		"\t\tplace-items: center;",
		"",
		"\t\tcolor: #000000;",
		"\t\tfont-size: 22px;",
		"\t\ttext-align: center;",
		"\t\ttext-decoration: none;",
		"",
		"\t\tcursor: pointer;",
		"",
		"\t\ttransition: .2s background-color;",
		"\t}",
		"",
		"\t.button:hover {",
		"\t\tbackground: #3000e040;",
		"\t}",
		"",
		"</style>",
		""
	].join("\n")
}
