export const tsconfig = [
	"{",
	"\t\"compilerOptions\": {",
	"\t\t/* - project options - */",
	"\t\t\"allowJs\": true,",
	"\t\t\"checkJs\": true,",
	"\t\t\"isolatedModules\": true,",
	"\t\t\"lib\": [ \"es2020\" ],",
	"\t\t\"module\": \"es2020\",",
	"\t\t\"removeComments\": true,",
	"\t\t\"sourceMap\": true,",
	"\t\t\"target\": \"es2019\",",
	"",
	"\t\t/* - strict checks - */",
	"\t\t\"alwaysStrict\": true,",
	"\t\t\"noImplicitAny\": true,",
	"\t\t\"noImplicitThis\": true,",
	"\t\t\"strict\": true,",
	"\t\t\"strictBindCallApply\": true,",
	"\t\t\"strictFunctionTypes\": true,",
	"\t\t\"strictNullChecks\": true,",
	"\t\t\"strictPropertyInitialization\": true,",
	"",
	"\t\t/* - linter checks - */",
	"\t\t\"noImplicitReturns\": true,",
	"\t\t\"noFallthroughCasesInSwitch\": true,",
	"\t\t\"noUncheckedIndexedAccess\": true,",
	"\t\t\"noUnusedLocals\": true,",
	"\t\t\"noUnusedParameters\": true,",
	"",
	"\t\t/* - module resolution - */",
	"\t\t\"baseUrl\": \".\",",
	"\t\t\"esModuleInterop\": true,",
	"\t\t\"moduleResolution\": \"node\",",
	"\t\t\"paths\": {",
	"\t\t\t\"lib/*\": [ \"src/lib/*\" ]",
	"\t\t},",
	"",
	"\t\t/* - advanced - */",
	"\t\t\"forceConsistentCasingInFileNames\": true,",
	"\t\t\"importsNotUsedAsValues\": \"error\",",
	"\t\t\"resolveJsonModule\": true,",
	"\t\t\"skipLibCheck\": true,",
	"\t},",
	"\t\"include\": [ \"src/**/*.d.ts\", \"src/**/*.js\", \"src/**/*.ts\", \"src/**/*.svelte\" ]",
	"}",
	""
].join("\n")

export const global = [
	"/// <reference types=\"@sveltejs/kit\" />",
	"/// <reference types=\"svelte\" />",
	"/// <reference types=\"vite/client\" />",
	""
].join("\n")
