export default [
	"{",
	"\t\"compilerOptions\": {",
	"\t\t/* - project options - */",
	"\t\t// \"allowJs\": true,",
	"\t\t// \"checkJs\": true,",
	"\t\t// \"composite\": true,",
	"\t\t\"declaration\": true,",
	"\t\t// \"declarationMap\": true,",
	"\t\t// \"downlevelIteration\": true,",
	"\t\t// \"importHelpers\": true,",
	"\t\t// \"incremental\": true,",
	"\t\t// \"isolatedModules\": true,",
	"\t\t// \"jsx\": \"preserve\",",
	"\t\t// \"lib\": [],",
	"\t\t\"module\": \"ES2020\",",
	"\t\t// \"noEmit\": true,",
	"\t\t\"outDir\": \"dist\",",
	"\t\t\"removeComments\": true,",
	"\t\t\"rootDir\": \"src\",",
	"\t\t// \"sourceMap\": true,",
	"\t\t\"target\": \"esnext\",",
	"\t\t// \"tsBuildInfoFile\": \"./\",",
	"",
	"\t\t/* - strict checks - */",
	"\t\t\"alwaysStrict\": true,",
	"\t\t\"noImplicitAny\": true,",
	"\t\t\"noImplicitThis\": true,",
	"\t\t\"strict\": true,",
	"\t\t\"strictBindCallApply\": true,",
	"\t\t\"strictFunctionTypes\": true,",
	"\t\t\"strictNullChecks\": true,",
	"\t\t\"strictPropertyInitialization\": true,",
	"",
	"\t\t/* - linter checks - */",
	"\t\t\"noFallthroughCasesInSwitch\": true,",
	"\t\t\"noImplicitReturns\": true,",
	"\t\t\"noUncheckedIndexedAccess\": true,",
	"\t\t\"noUnusedLocals\": true,",
	"\t\t\"noUnusedParameters\": true,",
	"",
	"\t\t/* - module resolution - */",
	"\t\t\"allowSyntheticDefaultImports\": true,",
	"\t\t// \"allowUmdGlobalAccess\": true,",
	"\t\t// \"baseUrl\": \"./\",",
	"\t\t\"esModuleInterop\": true,",
	"\t\t\"moduleResolution\": \"node\",",
	"\t\t// \"paths\": {},",
	"\t\t// \"preserveSymlinks\": true,",
	"\t\t// \"rootDirs\": [],",
	"\t\t// \"typeRoots\": [],",
	"\t\t// \"types\": [],",
	"",
	"\t\t/* - source maps - */",
	"\t\t// \"inlineSourceMap \": true,",
	"\t\t// \"inlineSources\": true,",
	"\t\t// \"mapRoot\": \"\",",
	"\t\t// \"sourceRoot\": \"\",",
	"",
	"\t\t/* - experimental - */",
	"\t\t\"emitDecoratorMetadata\": true,",
	"\t\t\"experimentalDecorators\": true,",
	"",
	"\t\t/* - advanced - */",
	"\t\t\"forceConsistentCasingInFileNames\": true,",
	"\t\t\"skipLibCheck\": true",
	"\t}",
	"}",
	""
].join("\n")
